- descriptions/SDK.NVIDIA_Ansel.md
- rules.ini
- tests/types/SDK.NVIDIA_Ansel.txt
- tests/types/_NonMatchingTests.txt
`(?:^|/)AnselSDK(?:|64)\.dll$`
Thanks,
Elliott
> Add NVIDIA Ansel

- descriptions/Container.Electron.md
- descriptions/Emulator.DOSBOX.md
- descriptions/Engine.Godot.md
- descriptions/Engine.GoldSource.md
- descriptions/Engine.Pico8.md
- descriptions/Engine.Unreal.md
- descriptions/Engine.idTech6.md
So here are the descriptions for a few game engines. Might be wrong on wording, but that's fine.
> Initial bulk of descriptions

- tests/FileDetector.php
Stuff I forgot in the other PR
> Godot fixes

- descriptions/Engine.Unigine.md
- rules.ini
- tests/types/Engine.Unigine.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/200390/
https://steamdb.info/app/552970/
https://steamdb.info/app/361550/
Added Unigine engine rules and tests for windows, linux and mac
> Add Unigine

- descriptions/AntiCheat.BattlEye.md
- descriptions/AntiCheat.PunkBuster.md
- descriptions/Emulator.SCUMMVM.md
- descriptions/Engine.AGI.md
- descriptions/Engine.AdobeAIR.md
- descriptions/Engine.AdobeFlash.md
- descriptions/Engine.AdventureGameStudio.md
- descriptions/Engine.Build.md
- descriptions/Engine.ChromeEngine.md
- descriptions/Engine.CryEngine.md
- descriptions/Engine.FNA.md
- descriptions/Engine.KiriKiri.md
- descriptions/Engine.Lime_OR_OpenFL.md
- descriptions/Engine.Love2D.md
- descriptions/Engine.MonoGame.md
- descriptions/Engine.Phyre.md
- descriptions/Engine.PlayFirstPlayground.md
- descriptions/Engine.Prism3D.md
- descriptions/Engine.Quake.md
- descriptions/Engine.RPGMaker.md
- descriptions/Engine.RenPy.md
- descriptions/Engine.VisionaireStudio.md
- descriptions/Engine.Wintermute.md
- descriptions/Engine.WolfRPGEditor.md
- descriptions/Engine.XNA.md
- descriptions/Engine.idTech2.md
- descriptions/Engine.idTech4.md
- descriptions/Engine.idTech5.md
- descriptions/SDK.NodeJS.md
Added missing descriptions
For now it's a draft until i finish doing missing ones and maybe change the ones i really don't like.
> Add Missing Descriptions

- descriptions/Engine.OGRE.md
- rules.ini
- tests/types/Engine.OGRE.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/200710/
https://steamdb.info/app/288750/
https://steamdb.info/app/270150/
https://steamdb.info/app/910830/
https://steamdb.info/app/404680/
https://steamdb.info/app/233860/
https://steamdb.info/app/23460/
https://steamdb.info/app/215160/
https://steamdb.info/app/339570/
Added OGRE engine rules and tests.
> Add OGRE engine support

- descriptions/Engine.Cocos2d.md
- rules.ini
- tests/types/Engine.Cocos2d.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/322170/
https://steamdb.info/app/613830/
https://steamdb.info/app/347280/
https://steamdb.info/app/491470/
https://steamdb.info/app/366260/
Add Cocos2d engine
> Add Cocos2d engine

- descriptions/SDK.Bink_Video.md
- rules.ini
- tests/types/SDK.Bink_Video.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/620/
https://steamdb.info/app/1328670/
https://steamdb.info/app/379720/
> Add Bink Video as SDK

- descriptions/Engine.Frostbite.md
https://steamdb.info/tech/Engine/Frostbite/
Fixed misspelling of the word Frostbite
> Fixed misspelling of Frostbite

- descriptions/SDK.OpenAL.md
- rules.ini
- tests/types/SDK.OpenAL.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/244770/
https://steamdb.info/app/323850/
https://steamdb.info/app/24010/
Add OpenAL as an SDK.
There seems to be quite a bit of custom name of dll so we will miss some
closes #88
> Add OpenAL as SDK

- descriptions/SDK.SteamworksNET.md
- rules.ini
- tests/types/SDK.SteamworksNET.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/504210/
https://steamdb.info/app/774791/
https://steamdb.info/app/620980/
https://steamdb.info/app/207140/
https://steamdb.info/app/261550/
Add detection for [Steamworks.NET](https://github.com/rlabrecque/Steamworks.NET).
> Add Steamworks.NET as SDK

- descriptions/Engine.RAGE.md
https://steamdb.info/tech/Engine/RAGE/
URL was missing for RAGE engine
> Fix missing link for RAGE

- descriptions/Engine.RealVirtuality.md
- rules.ini
- tests/types/Engine.RealVirtuality.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/107410/
https://steamdb.info/app/221100/
https://steamdb.info/app/33910/
https://steamdb.info/app/65730/
Add Real Virtuality Engine used in Bohemia Interactive's previous games :D
> Add Real Virtuality Engine

- descriptions/Engine.GameGuru.md
- rules.ini
- tests/types/Engine.GameGuru.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/799530
https://steamdb.info/app/1541110
https://steamdb.info/app/1090580
Added from a feature request. Closes #78.
> Add GameGuru

- descriptions/SDK.Intel_OID.md
- rules.ini
- tests/types/SDK.Intel_OID.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/250820
https://steamdb.info/app/1332010
https://steamdb.info/app/381210
Add Intel Open Image Denoise as an SDK
> Add Intel Open Image Denoise

- descriptions/SDK.OculusXRPlugin.md
- rules.ini
- tests/types/SDK.OculusXRPlugin.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/823500/
https://steamdb.info/app/242760/
https://steamdb.info/app/1599660/
https://steamdb.info/app/290510/
Add Oculus XR Plugin as an SDK
> Add Oculus XR Plugin

- descriptions/AntiCheat.AntiCheatExpert.md
- rules.ini
- tests/types/AntiCheat.AntiCheatExpert.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/578080/
https://steamdb.info/app/760160/
https://steamdb.info/app/760160/ (historically, they switched to EasyAntiCheat ~8 months ago)
https://steamdb.info/app/1008080/
https://steamdb.info/app/1371580/
https://steamdb.info/app/1674340/
Add detection for Anti-Cheat Expert developed anti-cheats.
> Add Anti-Cheat Expert

- descriptions/Engine.UbisoftAnvil.md
- rules.ini
- tests/types/Engine.UbisoftAnvil.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/15100/
https://steamdb.info/app/359550/
https://steamdb.info/app/2208920/
closes #169 
Add Ubisoft Anvil as an Engine
Afaik it doesn't have a website so i went with the wikipedia page
> Add Ubisoft Anvil

- descriptions/Engine.AmazonLumberyard.md
- rules.ini
- tests/types/Engine.AmazonLumberyard.txt
- tests/types/_NonMatchingTests.txt
(from #27 and #190)
https://steamdb.info/app/583240/
https://steamdb.info/app/2087030/
https://steamdb.info/app/1063730/
Added Amazon Lumberyard Engine detection
> Add Amazon Lumberyard

- descriptions/Engine.X-Ray.md
- rules.ini
- tests/types/Engine.X-Ray.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/franchise/S.T.A.L.K.E.R./
Added a rule for X-Ray, engine that powered S.T.A.L.K.E.R
> Add X-Ray Engine

- descriptions/AntiCheat.EAAntiCheat.md
- rules.ini
- tests/types/AntiCheat.EAAntiCheat.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1811260
Added rules for EA Anticheat
> Add EA AntiCheat

- descriptions/AntiCheat.Arbiter.md
- rules.ini
- tests/types/AntiCheat.Arbiter.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1240440/
Added Arbiter rules, for now its only used in Halo Infinite but might move onto next Halo games when they get released
> Add Arbiter

- descriptions/Launcher.EA_App.md
- rules.ini
- tests/types/Launcher.EA_App.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/publisher/Electronic+Arts/
Added rules for EA App detection
> Add EA App

- descriptions/Engine.4A_Engine.md
- rules.ini
- tests/types/Engine.4A_Engine.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/developer/4A+Games/
Added 4A Engine rule
> Add 4A Engine

- descriptions/SDK.Miles_Sound_System.md
- rules.ini
- tests/types/SDK.Miles_Sound_System.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1135240/
https://steamdb.info/app/201230/
https://steamdb.info/app/253920/
https://steamdb.info/app/2210/
closes #243 
Added a rule for Miles Sound System
> Add Miles Sound System

- descriptions/Engine.AppGameKit.md
- rules.ini
- tests/types/Engine.AppGameKit.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1585640/
https://steamdb.info/app/1698690/
https://steamdb.info/app/338000/
https://steamdb.info/app/500940/
and much more, im just lazy to look them up
Added AppGameKit rule
> Add AppGameKit

- descriptions/SDK.OpenSSL.md
- rules.ini
- tests/types/SDK.OpenSSL.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/529840/
https://steamdb.info/app/1238060/
https://steamdb.info/app/295950/
closes #253 
Added a rule for OpenSSL
> Add OpenSSL

- descriptions/SDK.NVIDIA_GeForce_Now.md
- rules.ini
- tests/types/SDK.NVIDIA_GeForce_Now.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1475810/
https://steamdb.info/app/1717020
https://steamdb.info/app/715400
closes #257 
Added a rule for NVIDIA GeForce Now, not sure about naming but let me know if its not right
> Add NVIDIA GeForce NOW (not sure about the naming)

- descriptions/SDK.Smacker_Video.md
- rules.ini
- tests/types/SDK.Smacker_Video.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/215930
https://steamdb.info/app/549170
https://steamdb.info/app/410980
closes #255 
Added a rule for Smacker Video
> Add Smacker Video

- descriptions/SDK.ZStandard.md
- rules.ini
- tests/types/SDK.ZStandard.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1255460/
closes #259 
Added a rule for Zstandard (zstd)
> Add ZStandard

- descriptions/Engine.REDengine.md
- rules.ini
- tests/types/Engine.REDengine.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/20920/
https://steamdb.info/app/292030/
https://steamdb.info/app/1091500/
closes #172 
Added a rule for REDengine
> Add REDengine

- descriptions/SDK.XAudio2.md
- rules.ini
- tests/types/SDK.XAudio2.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/730390/
https://steamdb.info/app/868270/
Closes #298 
Added a rule for XAudio2
> Add XAudio2

- descriptions/SDK.trueSKY.md
- rules.ini
- tests/types/SDK.trueSKY.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/495420/
https://steamdb.info/app/502500/
Added a rule for trueSKY SDK, the problem i am not sure that this regex gets all games because there's no mention of this sdk in some of the games listed on website (DayZ, Arma 3, Life is Strange 2) but maybe they're lying about it idk xd
> Add trueSKY

- descriptions/Engine.Phaser.md
- rules.ini
- tests/types/Engine.Phaser.txt
- tests/types/_NonMatchingTests.txt
I am not sure where to put it, but i guess it can be easily changed
https://steamdb.info/app/1131080/depots/
Added a rule for Phaser
> Add Phaser

- descriptions/AntiCheat.TenProtect.md
- rules.ini
- tests/types/AntiCheat.TenProtect.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/755790/
Added check for TenProtect anticheat, im not sure if thats the right file but its the only one that has TenProtect (TP) in the name *shrug*
> Add TenProtect

- descriptions/SDK.Tencent_GME.md
- rules.ini
- tests/types/SDK.Tencent_GME.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1008080/
https://steamdb.info/app/1281590/
https://steamdb.info/app/2249550/
Add Tencent GME as an SDK
> Add Tencent GME

- .github/labeler.yml
i don't know how to describe it, but we don't have a labeler rule for container stuff yet, y'all need to make a tag tho...
> Add a labeler rule for Container PRs

- descriptions/Engine.LithTech.md
- rules.ini
- tests/types/Engine.LithTech.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/21090/
https://steamdb.info/app/16450/
https://steamdb.info/app/206210/
https://steamdb.info/app/223650/
https://steamdb.info/app/241930/
https://steamdb.info/app/356190/
https://steamdb.info/app/837600/
https://steamdb.info/app/905640/
Find LithTech Engine. Closes #225.
> Add LithTech

- descriptions/Engine.Light.vn.md
- rules.ini
- tests/types/Engine.Light.vn.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1744570/info/
https://steamdb.info/app/2210980/info/
https://steamdb.info/app/1235400/info/
Adds detection for the Light.vn engine.
> Add detection for Light.vn game engine

- descriptions/SDK.Modio.md
- rules.ini
- tests/types/SDK.Modio.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1621690/
https://steamdb.info/app/244850/
https://steamdb.info/app/629760/
Add mod.io
closes  #570
> Add Mod.io

- descriptions/Engine.Silk.md
- rules.ini
- tests/types/Engine.Silk.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/216910/
https://steamdb.info/app/232750/
https://steamdb.info/app/303790/
https://steamdb.info/app/338390/
https://steamdb.info/app/1283400/
Detect Silk engine
> Add Silk Engine

- descriptions/AntiCheat.HackShield.md
- rules.ini
- tests/types/AntiCheat.HackShield.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/231060/
https://steamdb.info/app/384030/
https://steamdb.info/app/2241570/
Closes #283.
> Add HackShield

- descriptions/Launcher.Gaijin.md
- rules.ini
- tests/types/Launcher.Gaijin.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/386180/
https://steamdb.info/app/236390/
https://steamdb.info/app/884660/
closes #405
> Add Gaijin Launcher

- descriptions/Engine.FBN.md
- rules.ini
- tests/types/Engine.FBN.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1483570/
https://steamdb.info/app/2098090/
https://steamdb.info/app/2552850/
https://steamdb.info/app/2098090/
https://steamdb.info/app/1728690/
https://steamdb.info/app/2380090/
https://steamdb.info/app/1728680/
https://steamdb.info/app/986830/
https://steamdb.info/app/846700/
https://steamdb.info/app/646330/
https://steamdb.info/app/372930/
https://steamdb.info/app/528120/
https://steamdb.info/app/511140/
https://steamdb.info/app/990250/
https://steamdb.info/app/463060/
https://steamdb.info/app/615340/
Detect FBN Engine libraries.
> Add Fbn Engine

- descriptions/Launcher.Paradox_Launcher.md
- rules.ini
- tests/types/Launcher.Paradox_Launcher.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/394360/
https://steamdb.info/app/1158310/
> Add Paradox Launcher

- tests/FileDetector.php
- tests/Test.php
- tests/filelists/Engine.Godot.TestLinuxNoExt.txt
@akien-mga pls review (also maybe hop on our discord)
> Improve Godot matching

- descriptions/Engine.XNA.md
https://steamdb.info/tech/Engine/XNA/
Change `developped` to `developed`
> Fix typo in Engine.XNA.md

- descriptions/SDK.YarnSpinner.md
- rules.ini
- tests/types/SDK.YarnSpinner.txt
- tests/types/_NonMatchingTests.txt
* [Night in the Woods](https://store.steampowered.com/app/481510/Night_in_the_Woods/)
* [Dredge](https://store.steampowered.com/app/1562430/DREDGE/)
* [Venba](https://store.steampowered.com/app/1491670/Venba/)
* [Lost in Random](https://store.steampowered.com/app/1462570/Lost_in_Random/)
* [A Short Hike](https://store.steampowered.com/app/1055540/A_Short_Hike/)
This PR adds rules for detecting the Yarn Spinner narrative system, as well as tests and supporting files.
> Add Yarn Spinner

- descriptions/Engine.Buddha.md
- rules.ini
- tests/types/Engine.Buddha.txt
- [Brütal Legend](https://steamdb.info/app/225260/)
- [Costume Quest](https://steamdb.info/app/115100/)
- [Costume Quest 2](https://steamdb.info/app/275180/)
- [Headlander](https://steamdb.info/app/340000/)
- [Iron Brigade](https://steamdb.info/app/115120/)
- [Massive Chalice](https://steamdb.info/app/246110/)
- [Stacking](https://steamdb.info/app/115110/)
- [The Cave](https://steamdb.info/app/221810/)
added a rule for Buddha engine
> add Buddha

- descriptions/AntiCheat.AnyBrain.md
- rules.ini
- tests/types/AntiCheat.AnyBrain.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/depot/1599341/history/?changeid=M:6557352479356837685
https://steamdb.info/depot/1789481/history/?changeid=M:5820253887811004766
Added support for detecting AnyBrain AntiCheat by searching for the existence of the anybrainSDK.dll SDK.
> Add AnyBrain AntiCheat

- descriptions/Engine.3D_GameStudio.md
- rules.ini
- tests/types/Engine.3D_GameStudio.txt
- tests/types/_NonMatchingTests.txt
- [AaaaaAAaaaAAAaaAAAAaAAAAA!!! - A Reckless Disregard for Gravity](https://steamdb.info/app/15520/)
- [Bad Rats: The Rats' Revenge](https://steamdb.info/app/34900/)
- [Dark Shadows: Army of Evil](https://steamdb.info/app/280640/)
- [Guise of the Wolf](https://steamdb.info/app/259640/)
- [The Wonderful End of the World](https://steamdb.info/app/15500/)
closes #70
> add 3D GameStudio

- descriptions/SDK.FishNet.md
- rules.ini
- tests/types/SDK.FishNet.txt
- tests/types/_NonMatchingTests.txt
https://store.steampowered.com/app/3164500/Schedule_I/
- Add detection for FishNet networking library
> Add detection for FishNet multiplayer library

- rules.ini
- tests/types/Emulator.DOSBOX.txt
> dosbox.exe

- descriptions/SDK.Resonance_Audio.md
- rules.ini
- tests/types/SDK.Resonance_Audio.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/301520/
https://steamdb.info/app/330020/
https://steamdb.info/app/290340/
Add Resonance Audio, a now archived spacial audio plugin developed by google
> Add Resonance Audio
