- descriptions/SDK.SteamNetworking.md
- rules.ini
- tests/types/SDK.SteamNetworking.txt
- tests/types/_NonMatchingTests.txt
`(?:^|/)(?:stun_)steamnetworking(?:sockets).(?:dylib|dll|so)$`
The stun part is there due to [Battlerite](https://steamdb.info/app/504370/) having it, i'm not sure if any other game has a modified lib name
> Add Steam Networking

- descriptions/SDK.Steam_Audio.md
- rules.ini
- tests/types/SDK.Steam_Audio.txt
- tests/types/_NonMatchingTests.txt
`(?:^|/)(?:lib)?steamaudio\.(?:dylib|dll|so)`
From my installed game, i didn't find any game with a mac version that had steam audio but i'll futur proof and add `dylib`
Sadly, i don't think there's way to detect Steam Audio if it's used with the fmod sound engine integration because they call the lib `phonon.dll` and i think that, from my small search, this name is not specific to Steam Audio, so using it might cause false positive
> Add Steam Audio

- descriptions/SDK.AMD_GPU_Services.md
- rules.ini
- tests/types/SDK.AMD_GPU_Services.txt
- tests/types/_NonMatchingTests.txt
`(?:^|/)amd_ags_x(?:64|86).dll$`
From my search, this is a windows only lib.
> Add AMD GPU Services

- descriptions/AntiCheat.nProtect_GameGuard.md
- rules.ini
- tests/types/AntiCheat.nProtect_GameGuard.txt
- tests/types/_NonMatchingTests.txt
[Phantasy Star Online 2](https://steamdb.info/app/1056640/)
[CABAL Online](https://steamdb.info/app/253490/)
Added the anti-cheat [nProtect GameGuard](https://en.wikipedia.org/wiki/nProtect_GameGuard) ([official site](https://gameguard.nprotect.com/)). May also match to `npptnt2.sys` per [this](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2005-0295) CVE, however not sure if there are any games on Steam that use this filename.
Thanks,
Elliott
> Add nProtect GameGuard

- descriptions/SDK.Qt.md
- rules.ini
- tests/types/SDK.Qt.txt
- tests/types/_NonMatchingTests.txt
Games using this SDK:
- [Half-Life: Alyx](https://steamdb.info/app/546560)
- [s&box](https://steamdb.info/app/590830)
- [Dota 2](https://steamdb.info/app/570)
- [Cyberpunk 2077](https://steamdb.info/app/1091500)
- [ARK: Survival Evolved](https://steamdb.info/app/346110)
The main target file is basically `Qt5Core.dll`, Alyx uses Qt4 rather than Qt5 and its core file name is `QtCore4.dll`.
> Add a new SDK Qt

- rules.ini
- tests/types/Engine.Godot.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/404790/
`project.godot` is a file which should be included with any source code distribution
for Godot engine.
Most games do not ship with source code of course, but some might, and the
Godot Engine app itself ships with demos source code, which should be matched
by this rule.
**PLEASE TEST.** I did not test it myself. It should match at least [Godot Engine](https://steamdb.info/app/404790/), and might match a few other entries if they ship Godot source code.
I found one Godot game which is currently not matched because it's shipped as a full source code release only: https://steamdb.info/app/808580
But it's a Godot 2.1 game and there the engine entry point was named `engine.cfg`, which is IMO too common a name to use as evidence for Godot, even if it's a strong …
> Detect projects with Godot source code (`project.godot`)

- descriptions/Engine.Virtools.md
- rules.ini
- tests/types/Engine.Virtools.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/46500/
https://steamdb.info/app/46510/
https://steamdb.info/app/832540/
https://steamdb.info/app/46550/
https://steamdb.info/app/46480/
https://steamdb.info/app/34800/
Add Virtools engine. It's used in Syberia, Syberia 2, and some other old games.
Its distinctive files - CK2.dll, CK2_3D.dll, VirtoolsLoader.dll(or VirtoolsLoaderR.dll), and either one of CKDX7Rasterizer.dll, CKDX8Rasterizer.dll, CKDX9Rasterizer.dll. The rule is set to detect one of the latter ones.
> Add Virtools engine

- descriptions/Engine.HashLink.md
- rules.ini
- tests/types/Engine.HashLink.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/588650/
https://steamdb.info/app/466560/
https://steamdb.info/app/939100/
https://steamdb.info/app/1527950/
https://steamdb.info/app/1020470/
Add HashLink engine. This is a bytecode virtual machine based on Haxe. Used by the above games (Dead Cells, Northgard, more).
> add HashLink engine

- descriptions/Engine.Kex.md
- rules.ini
- tests/types/Engine.Kex.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1148590/
https://steamdb.info/app/1010750/
https://steamdb.info/app/2310/
https://steamdb.info/app/410710/
https://steamdb.info/app/405820/
https://steamdb.info/app/668980/
Add Kex engine. It is used by Nightdive Studios to remaster old titles like Doom 64, Blood, Turok, System Shock, recently released Quake 2021 rerelease, etc.
> Add Kex engine

- descriptions/Engine.Torque.md
- rules.ini
- tests/types/Engine.Torque.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/250340/
https://steamdb.info/app/375810/
https://steamdb.info/app/18700/
https://steamdb.info/app/98200/
This adds detection for `.cs.dso` files in for Torque engine, as most Torque games use compiled DSO script files.
Closes #86.
> Add Torque engine

- descriptions/SDK.UnityURP.md
- rules.ini
- tests/types/SDK.UnityURP.txt
https://steamdb.info/app/1307550
https://steamdb.info/app/1062090
https://steamdb.info/app/1158370/
Adds unity's Universal Render Pipeline, which is a Scriptable render pipeline. Unity has two, HDRP and URP, and they're the new and supported 'graphic' backends of unity. The old one is on long-term bug fixing only.
View #96 for more info.
> Adding Unity's Universal Render Pipeline as SDK

- descriptions/AntiCheat.EQU8.md
- rules.ini
- tests/types/AntiCheat.EQU8.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/824270/
https://steamdb.info/app/677620/
https://steamdb.info/app/823130/
Adds detection support for EQU8 Anti-Cheat under AntiCheat section by finding `equ8_conf.json` which is required for EQU8 Anti-Cheat.
(There are additional detection vectors available as well but these are the main ones that are mentioned in the [documentation for anticheat distribution](https://equ8.gitbook.io/documentation/integration-guide/distributing-with-equ8)
> Add detection vectors for EQU8 Anti-Cheat

- tests/FileDetector.php
- tests/filelists/Engine.Godot.TestLinux32.txt
- tests/filelists/Engine.Godot.TestLinux32Old.txt
- tests/filelists/Engine.Godot.TestLinux64.txt
- tests/filelists/Engine.Godot.TestMacOS.txt
- tests/filelists/Engine.Godot.TestWindows.txt
None yet, it's future proofing for Godot 4.0.
The extension changed from .x86 to .x86_32 in Godot 4.0.
Ref. https://github.com/godotengine/godot/pull/59394
> Godot: Add support for .x86_32 extension for Linux x86 32-bit

- descriptions/SDK.Vorbis.md
- rules.ini
- tests/types/SDK.Vorbis.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/621060/
https://steamdb.info/app/22300/
https://steamdb.info/app/1599340/
https://steamdb.info/app/1200/
Add Vorbis as an sdk
Such a loose rule could lead to some false positive but it seems unlikely to me, with such an unusual word that it would be unrelated to the codec
> Add Vorbis

- descriptions/SDK.OpenXR.md
- rules.ini
- tests/types/SDK.OpenXR.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/250820/
https://steamdb.info/app/236390/
https://steamdb.info/app/1128920/
Add OpenXR as an SDK
I'm not a big fan of the description i took from their website since, imo, we are talking about the loader not the standard but 🤷
> Add OpenXR

- descriptions/Engine.UbiArtFramework.md
- rules.ini
- tests/types/Engine.UbiArtFramework.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/260230/
https://steamdb.info/app/446560/
https://steamdb.info/app/256290/
Add UbiArt Framework as an Engine
i thought about putting UbiArt's blog that was up until 2015 but there isn't really anything interesting on it and it seems that wayback machine only stored the main page
https://web.archive.org/web/20150726105038/http://ubi-art.uk.ubi.com/
> Add UbiArt Framework

- .github/ISSUE_TEMPLATE/6_type_sdk.yml
Noticed this in https://github.com/SteamDatabase/FileDetectionRuleSets/issues/131
> [Minor, meta] Fix SDK template to actually add the SDK label

- descriptions/Engine.Torque.md
Updates the Torque Game Engine description to point to the current website, rather than the old, defunct garagegames.com one
> Updates Torque Game Engine description's website link

- descriptions/SDK.UnityBurst.md
- rules.ini
- tests/types/SDK.UnityBurst.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1062090/
https://steamdb.info/app/1837750/
Adds detection for the unity Burst sdk which is used to compile IL/.NET bytecode into native code.
> Adds detection for games utilising the burst compiler.

- descriptions/SDK.AMD_FSR2.md
- rules.ini
- tests/types/SDK.AMD_FSR2.txt
- tests/types/_NonMatchingTests.txt
[Marvel’s Spider-Man Remastered](https://store.steampowered.com/app/1817070/Marvels_SpiderMan_Remastered/)
Add rules for AMD FidelityFX Super Resolution 2 (FSR2).
> Add rules for AMD FSR2

- descriptions/SDK.NWJS.md
- rules.ini
- tests/types/SDK.NWJS.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/281610
https://steamdb.info/app/363890
Add NW.js as an SDK
closes #67 
The description could probably be improved but that "lib" doesn't have a wiki page so i'm not sure what more can be said
> Add NW.js as an SDK

- descriptions/SDK.iZotope.md
- rules.ini
- tests/types/SDK.iZotope.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/883710/
https://steamdb.info/app/1525621/
https://steamdb.info/app/1818750/
https://steamdb.info/app/1120480/
I did also find https://steamdb.info/app/939510/, which seems to be a weirder case, as it's literally bundling some of the iZotope plugins you're supposed to make music with, not bundle in games as a dll.
Added the iZotope SDK. I would say this is fairly noteworthy; if Wwise itself is in here, and games like Resident Evil 2/3 use this as a standalone SDK, it should be well-known enough.
> added iZotope's SDK

- descriptions/Engine.Diesel.md
- rules.ini
- tests/types/Engine.Diesel.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/21680
https://steamdb.info/app/218620/
https://steamdb.info/app/414740/
Add Diesel as a game engine
closes #175 
this one misses 2 games that aren't really easy to detect so i'll open an issue about them ([Tom Clancy's Ghost Recon: Advanced Warfighter](https://steamdb.info/app/13640/) & [Tom Clancy's Ghost Recon: Advanced Warfighter 2](https://steamdb.info/app/13510/))
> Add Diesel

- descriptions/Engine.Glacier.md
- rules.ini
- tests/types/Engine.Glacier.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/236870/
https://steamdb.info/app/863550/
https://steamdb.info/app/1659040/
Add Glacier as an Engine
For now it only matches the last "batch" of hitman games, but previous hitman games also used this engine so i'll either update this pr or do a new one to also match them
> Add Glacier

- descriptions/Engine.EngineX.md
- rules.ini
- tests/types/Engine.EngineX.txt
* [*Sphinx and the Cursed Mummy*](https://steamdb.info/app/606710/)
* [*Pirates of the Caribbean: At World's End*](https://steamdb.info/app/301980/)
* [*G-Force*](https://steamdb.info/app/319170/)
* [*Beijing 2008*](https://steamdb.info/app/10520/)
* [*Vancouver 2010*](https://steamdb.info/app/34180/)
* [*Disney Universe*](https://steamdb.info/app/316260/)
* [*007 Legends*](https://steamdb.info/app/211670/)
Add support for detecting EngineX, used by many 2001+ Eurocom games, from Pirates of the Caribbean, to 007, to adventure games like G-Force, Robots (2005), and Sphinx and the Cursed Mummy as well as Olympic games.
https://sphinxandthecursedmummy.fandom.com/wiki/EngineX
```
data/Filelist.bin
_bin_PC/BuildData/Filelist.bin
_bin_PC/BuildData/Filelist.cfi
PCAudio.dll
```
Some other unique …
> Add support for detecting EngineX, used by many 2001+ Eurocom games

- descriptions/SDK.DirectStorage.md
- rules.ini
- tests/types/SDK.DirectStorage.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/2195250/
https://steamdb.info/app/1895880/
https://steamdb.info/app/1680880/
Add DirectStorage as an SDK
Closes #445
i'm not a fan of linking to a github repo, i'll have to look if they don't have a website with more info
> Add DirectStorage as an SDK

- descriptions/SDK.NVIDIA_Highlights.md
- rules.ini
- tests/types/SDK.NVIDIA_Highlights.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/1449560/depots/
added a rule for NVIDIA Highlights (SDK for using NVIDIA Share features, as dll description states)
> add NVIDIA Highlights

- rules.ini
- tests/types/SDK.NVIDIA_Reflex.txt
https://steamdb.info/depot/1938091
This dll is actually a part of a bigger SDK called Streamline (#509), but i guess we could use it in both?
> Update NVIDIA Reflex

- KNOWN_UNDETECTIONS.md
https://steamdb.info/app/2084620/
https://steamdb.info/app/1083480/
https://steamdb.info/app/952330/
https://steamdb.info/app/2061580/
https://steamdb.info/app/1117420/
https://steamdb.info/app/2166200/
https://steamdb.info/app/1275210/
https://steamdb.info/app/710550/
https://steamdb.info/app/1782940/
https://steamdb.info/app/1213460/
https://steamdb.info/app/2333820/
https://steamdb.info/app/298180/
https://steamdb.info/app/2545810/
https://steamdb.info/app/427920/
https://steamdb.info/app/763610/
https://steamdb.info/app/1279000/
https://steamdb.info/app/1384400/
https://steamdb.info/app/713540/
https://steamdb.info/app/702150/
https://steamdb.info/app/930310/
https://steamdb.info/app/1683890/
https://steamdb.info/app/2233040/
https://steamdb.info/app/1394370/ …
> Add Clickteam Fusion to KNOWN_UNDETECTIONS.md

- rules.ini
- tests/types/SDK.UnityEntities.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/2162310/
https://steamdb.info/app/2132350/
https://steamdb.info/app/2783610/
`StreamingAssets/SubScenes/` is no longer used in recent versions, `StreamingAssets/EntityScenes/` replaces it.
> update SDK.UnityEntities rule

- descriptions/Engine.GameBox.md
- rules.ini
- tests/types/Engine.GameBox.txt
- tests/types/_NonMatchingTests.txt
- [Trackmania](https://steamdb.info/app/2225070/)
- [Trackmania² Lagoon](https://steamdb.info/app/600720/)
- [Trackmania® Turbo](https://steamdb.info/app/375900/)
- [TrackMania² Valley](https://steamdb.info/app/243360/)
- [TrackMania² Stadium](https://steamdb.info/app/232910/)
- [TrackMania² Canyon](https://steamdb.info/app/228760/)
- [TrackMania Nations Forever](https://steamdb.info/app/11020/)
- [Trackmania United Forever](https://steamdb.info/app/7200/)
Find Nadeo.ini
> Add GameBox engine

- rules.ini
- tests/types/SDK.CRIWARE.txt
- tests/types/_NonMatchingTests.txt
https://steamdb.info/app/2243710/
https://steamdb.info/app/2985890/
https://steamdb.info/app/2512840/
Find cri_ware_unity.dll - the DLL used by the official CRIWARE Unity plugin.
> Update CRIWARE Unity detection

- descriptions/Engine.Divinity_Engine.md
- rules.ini
- tests/types/Engine.Divinity_Engine.txt
- tests/types/_NonMatchingTests.txt
- [Baldur's Gate 3](https://steamdb.info/app/1086940/)
- [Divinity: Original Sin](https://steamdb.info/app/230230/)
- [Divinity: Original Sin - Enhanced Edition](https://steamdb.info/app/373420/)
- [Divinity: Original Sin II](https://steamdb.info/app/435150/)
- [Divinity: Original Sin II - Definitive Edition](https://steamdb.info/app/435150/)
aand I'm back again with yet another rule from my old fork, thanks gibbed for the suggestion
> Add Divinity Engine

- descriptions/Engine.IRISZOOM.md
- rules.ini
- tests/types/Engine.IRISZOOM.txt
- tests/types/_NonMatchingTests.txt
- [Act of Aggression](https://steamdb.info/app/318020/)
- [R.U.S.E.](https://steamdb.info/app/21970/)
- [Steel Division 2](https://steamdb.info/app/919640/)
- [Steel Division: Normandy 44](https://steamdb.info/app/572410/)
- [Wargame: Airland Battle](https://steamdb.info/app/222750/)
- [Wargame: European Escalation](https://steamdb.info/app/58610/)
- [Wargame: Red Dragon](https://steamdb.info/app/251060/)
- [WARNO](https://steamdb.info/app/1611600/)
should be the last pr for a while
> Add IRISZOOM

- descriptions/SDK.E-mote.md
- rules.ini
- tests/types/SDK.E-mote.txt
- tests/types/_NonMatchingTests.txt
- [NEKOPARA Vol. 0](https://steamdb.info/depot/385801/)
- [NEKOPARA Vol. 1](https://steamdb.info/depot/333601/)
- [NEKOPARA Vol. 2](https://steamdb.info/depot/420111/)
- [NEKOPARA Vol. 3](https://steamdb.info/depot/602521/)
- [NEKOPARA Vol. 4](https://steamdb.info/depot/1406991/)
- [NEKOPARA Extra](https://steamdb.info/depot/899971/)
- [KukkoroDays](https://steamdb.info/depot/1258341/)
- [TroubleDays](https://steamdb.info/depot/1171271/)
- [IdolDays](https://steamdb.info/depot/1576131/)
- [NinNinDays](https://steamdb.info/depot/1075981/)
- [NinNinDays2](https://steamdb.info/depot/1698031/)
- [NekoMiko](https://steamdb.info/depot/969701/)
- [Fantasy Tavern Sextet -Vol.1 New World Days-](https://steamdb.info/depot/1372831/)
- [Fantasy Tavern Sextet -Vol.2 Adventurer's …
> Add E-mote

- descriptions/Engine.VisualNovelMaker.md
Corrected a typo in the description ('creaitng' to 'creating').
> Fix typo in Visual Novel Maker description.

- rules.ini
- tests/types/SDK.Yarn_Spinner.txt
- tests/types/_NonMatchingTests.txt
* [The Berlin Apartment](https://steamdb.info/app/3153440/depots/)
* [Little Nemo and the Guardians of Slumberland ](https://steamdb.info/app/2440530/depots/)
If a game is made in Unity and IL2CPP is used, the usual YarnSpinner.dll will not be present. Instead, depending on what parts of Yarn Spinner have been used, new .dat files will be emitted with these patterns.
As Yarn Spinner is primarily an unpaid project, and we use no analytics, getting an accurate read on how many people use the tool is one of our primary ways of keeping track of the project. We are super, super grateful that a tool like SteamDB exists.
> Yarn Spinner detection if IL2CPP is also used
